Add default case for docker-service (with error)

diff --git a/docker/base/centos-7/conf/bin/usr-bin/docker-service b/docker/base/centos-7/conf/bin/usr-bin/docker-service
--- a/docker/base/centos-7/conf/bin/usr-bin/docker-service
+++ b/docker/base/centos-7/conf/bin/usr-bin/docker-service
@@ -80,6 +80,10 @@ for SERVICE in "$@"; do
             service "${SERVICE}" "$SERVICE_COMMAND"
             ;;
 
+         *)
+            echo "[ERROR] $SERVICE_COMMAND is not a valid command"
+            exit 1
+            ;;
     esac
 done
 
