Add docker-service run command

diff --git a/docker/base/debian-8/conf/bin/usr-bin/docker-service b/docker/base/debian-8/conf/bin/usr-bin/docker-service
--- a/docker/base/debian-8/conf/bin/usr-bin/docker-service
+++ b/docker/base/debian-8/conf/bin/usr-bin/docker-service
@@ -14,6 +14,7 @@ SERVICE_COMMAND=$1
 shift
 
 for SERVICE in "$@"; do
+    RUN_FILE="/opt/docker/bin/service.d/${SERVICE}.sh"
     SERVICE_FILE="/opt/docker/etc/supervisor.d/${SERVICE}.conf"
     PROVISION_FILE="/opt/docker/provision/service.d/${SERVICE}.sh"
 
@@ -63,6 +64,15 @@ for SERVICE in "$@"; do
 
                 ## remove directory (one run time)
                 rm -f -- "$PROVISION_FILE"
+            fi
+            ;;
+
+        run)
+            if [[ -f "$RUN_FILE" ]]; then
+                exec "$RUN_FILE"
+            else
+                echo "[ERROR] Service '${SERVICE}' not found (tried ${RUN_FILE})"
+                exit 1
             fi
             ;;
 
