Added service control script

diff --git a/_localscripts/usr/local/bin/service b/_localscripts/usr/local/bin/service
--- a/_localscripts/usr/local/bin/service
+++ b/_localscripts/usr/local/bin/service
@@ -5,23 +5,51 @@ set -o errtrace  # trace ERR through 'time command' and other functions
 set -o nounset   ## set -u : exit the script if you try to use an uninitialised variable
 set -o errexit   ## set -e : exit the script if any statement returns a non-true return value
 
-if [ "$#" -lt 2 ]; then
-    echo "[ERROR] Usage: ${basename "$0"} <servicename> <stop|start|restart|pid>"
+# Root check
+if [ "$(/usr/bin/whoami)" != "root" ]; then
+    echo "[ERROR] Must be run as root"
     exit 1
 fi
+
+function serviceHelp() {
+    echo "Usage: $(basename "$0") <servicename> <stop|start|restart|pid|status>"
+}
+
+# Param check
+if [ "$#" -lt 2 ]; then
+    echo "[ERROR] Missing parameters"
+    serviceHelp
+    exit 1
+fi
+
+#############################
+# Param init
+#############################
 
 SERVICENAME="$1"
 ACTION="$2"
 
+#############################
+# Service aliases
+#############################
+case "$SERVICENAME" in
+    apache2|httpd)
+        SERVICENAME="apache"
+        ;;
+esac
+
+#############################
+# Action runner
+#############################
 case "$ACTION" in
-    "stop")
-    "start")
-    "restart")
-        exec supervisorctl "$ACTION" "${SERVICENAME}:*"
+    stop|start|restart|pid|status)
+        exec supervisorctl "$ACTION" "${SERVICENAME}:${SERVICENAME}d"
         ;;
 
-    "pid")
-        exec supervisorctl "pid" "${SERVICENAME}:${SERVICENAME}d"
+    *)
+        echo "[ERROR] Invalid action"
+        serviceHelp
+        exit 1
         ;;
 
 esac
